---
abstract: 'This module converts numbers (cardinals and ordinals) into their Bask (Euskara) equivalents.'
author:
  - 'Isabelle Hernandez <isabelle@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EUS-Numbers
requires:
  Carp: 0
  Exporter: 0
  strict: 0
  vars: 0
  warnings: 0
version: 0.044
